### ISSUE TITLE
Searching with non-standard characters produces 500 internal server error

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/realestate#104]
Needs to display "x results..." but currently does nothing.

**Comment by ThomasThoren** [comment]
Fixed. It is even prepared for the advent of emojis in land records.

 
<img width="208" alt="screen shot 2016-09-12 at 1 05 20 pm" src="https://cloud.githubusercontent.com/assets/5692185/18446841/9f1c1e9a-78e9-11e6-9e5c-01857a384dfc.png">

**Comment by myersnews** [comment]
:)

--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
