### ISSUE TITLE
ZIP code search doesn't work if it's not filled in

### ISSUE THREAD

**Issue by myersnews** [TheLens/realestate#117]
Example: This one didn't come up because they didn't enter a ZIP http://vault.thelensnola.org/realestate/sale/2016-03194

I guess we need to create the ZIP if it's not there. I wonder how many properties this is affecting.

**Comment by ThomasThoren** [comment]
I'm not sure I understand. How did you find that sale? How were you trying to find it?

**Comment by myersnews** [comment]
I was searching by ZIP code and it didn't come up. After a couple weeks, I figured it had to be in the system, so I searched by "freret" (this is next to deirdre, reb's mom)

**Comment by ThomasThoren** [comment]
If you search with a ZIP of 70118, it shows up on page 2.

I recently added the second half of January all in one go, which might explain why it was missing in the past but is there now. Our password expired this month, so the app was stuck on early January for a week or two. It should be all caught up now though.

**Comment by myersnews** [comment]
ok, maybe that’s it. so does the app figure out a ZIP for every address?
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Yes, as long as the geocoding is accurate enough to trust. Same thing with neighborhoods.

**Comment by myersnews** [comment]
aha. I figured the problem was that the court employee didn’t enter a ZIP.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
