### ISSUE TITLE
Double-check on social tags

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/realestate#45]
Make sure Open Graph tags are up-to-date for Facebook and Twitter.

**Comment by myersnews** [comment]
Social buttons share the main search URL, not the results page. Is that what you want?

**Comment by ThomasThoren** [comment]
That was my intention, yeah. It seems like it would be better to have a single URL, the main entrance to the app, kicking around social media. Users still have the option to share their specific page by copying the URL in their browser, if that's what they want.

**Comment by myersnews** [comment]
I think I need feedback from someone who has done this a lot to see if we should put those buttons on.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
@myersnews, let me know if this language is okay.

Twitter cards:
![screen shot 2015-02-20 at 9 09 22 am](https://cloud.githubusercontent.com/assets/5692185/6288678/515b0f74-b8e0-11e4-95a3-46158d12754c.png)

Facebook sharing:
![screen shot 2015-02-20 at 9 10 00 am](https://cloud.githubusercontent.com/assets/5692185/6288682/55137372-b8e0-11e4-9440-d2ca59bd9366.png)

**Comment by myersnews** [comment]
Suggest:

A map of every property sale in New Orleans, updated daily with prices, addresses, buyers and sellers. Search across the city or in your neighborhood.
 
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
